name: FenicsConcrete
channels:
  - conda-forge
  - bam77
  - defaults
dependencies:
  - python=3.9.7
  - fenics=2019.1.0
  - python-gmsh
  - meshio
  - matplotlib
  - mamba
  - scipy
  - numpy
  - pytest
  - loguru
  - pip
  - pip:
    - -e .
