{% set name = "fenicsconcrete" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/BAMresearch/FenicsConcrete

build:
  number: 1
  skip: true   # dont know why but it works...
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    
  host:
    - python
    - pip
    
  run:
    - python
    - fenics=2019.1.0
    - scipy>=1
    - numpy>=1
    - loguru<1

test:
  imports:
  requires:
  commands:

about:
  home: https://github.com/BAMresearch/FenicsConcrete
  summary: 'A Python package for a FEM concrete model based on fenics'
  license: MIT

extra:
  recipe-maintainers:
    - etamsen
