{% set name = "fenics_concrete" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/BAMresearch/FenicsConcrete

build:
  number: 0
  skip: true   # dont know why but it works...
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    
  host:
    - python
    - pip
    
  run:
    - python
    - fenics=2019.1.0
    - scipy>=1
    - numpy>=1
    - loguru<1

test:
  imports:
    - fenics_concrete
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - pytest tests

about:
  home: https://github.com/BAMresearch/FenicsConcrete
  summary: 'A Python package for a FEM concrete model based on fenics'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - etamsen
