{% set name = "fenics_concrete" %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name|lower }}
  version: {{ data['version'] }}

source:
  git_url: https://github.com/BAMresearch/FenicsConcrete

build:
  number: 0
  skip: true   # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - git
  host:
    - python=3.9
    - pip
    
  run:  
    - python=3.9.7
    - fenics=2019.1.0
    - python-gmsh
    - meshio
    - matplotlib
    - scipy
    - numpy
    - pytest
    - loguru

test:
  imports:
  requires:
  commands:

about:
  home: https://github.com/BAMresearch/FenicsConcrete
  summary: 'A Python package for a FEM concrete model based on fenics'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - etamsen
