name: publish_conda

on:
  release:
    types: [published]
  # for testing
  workflow_dispatch:
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          python-version: 3.9
          channels: conda-forge, hannes2621, defaults
          channel-priority: true

      - name: Build and upload
        shell: bash -l {0}
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          mamba config --set anaconda_upload yes
          mamba install boa
          mamba install anaconda-client
          mamba install conda-verify
          cd $GITHUB_WORKSPACE
          mamba mambabuild --token "6424080f33829b3c7e0bf816" -- user testuser77 .
