# This workflow will install Python dependencies, run tests with concrete model
name: Tests for fenics concrete

on:
  push:
    branches-ignore:

  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  testing_tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: setup-conda-environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          mamba-version: "*"
          auto-update-conda: true
          activate-environment: FenicsConcrete
       
      
      - name: testing packages
        shell: bash -l {0}
        run: |
          conda info
          conda list
      
      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest
      
      
            
        
