# This workflow will install Python dependencies, run tests with concrete model
name: Tests for fenics concrete

on:
  push:
    branches-ignore:

  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs the workflow once per day at 3:15am
  schedule:
    - cron: '3 15 * * *'

#env:
#  CACHE_NUMBER: 2  # increase to reset cache manually

jobs:
  testing_tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: FenicsConcrete
            use-mamba: true
            python-version: 3.9

#      - name: Set cache date
#        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

#      - uses: actions/cache@v2
#        with:
#          path: "/usr/share/miniconda3/envs/fenics_concrete"
#          key: conda-${{ hashFiles('environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
#        id: cache

      - name: Update environment
        run: mamba env update -n FenicsConcrete -f environment.yml
#        if: steps.cache.outputs.cache-hit != 'true'
      
      - name: Run tests
        shell: bash -l {0}
        run: |
#          cd $GITHUB_WORKSPACE/tests/
          pytest
      
      
            
        
